name: Convert README.ipynb to README.md

on:
  push:
    branches:
      - test-action
    paths:
      - 'README.ipynb'

jobs:
  convert-to-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Jupyter Notebooks to Markdown
        uses: VladimirFokow/Jupyter-to-Markdown@v1

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Automatically converted .ipynb to .md" --author "GitHub Actions <actions@github.com>"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
