name: Convert README.ipynb to README.md

on:
  push:
    paths:
      - 'README.ipynb'

jobs:
  convert-readme--jupytext:
    runs-on: ubuntu-latest

    steps:
      - name: Download jupytext
        run: pip install jupytext --upgrade

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert .ipynb to .md
        run: |
          jupytext --to md --update-metadata '{"jupytext": {"notebook_metadata_filter": "-all"}}' README.ipynb

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Automatically converted .ipynb to .md" --author "GitHub Actions <actions@github.com>"  || exit 0

      - name: Pull any additional changes  (and rebase)
        run: git pull --rebase origin ${{ github.ref }}
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
