name: Convert README.ipynb to README.md

on:
  push:    
    branches:
      - test-action
    paths:
      - 'README.ipynb'

jobs:
  convert-readme--autopy-lot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: autopy-lot (doing .ipynb conversion)
        uses: deep5050/autopy-lot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input_type: ipynb
          output_type: markdown
          output_dir: ./autopy-lot/
