name: Convert README.ipynb to README.md

on:
  push:    
    branches:
      - test-action
    paths:
      - 'README.ipynb'

jobs:
  convert-readme--autopy-lot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: autopy-lot (doing .ipynb conversion)
        uses: deep5050/autopy-lot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input_type: ipynb
          output_type: markdown
          output_dir: ./autopy-lot/

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatically converted .ipynb to .md" --author "GitHub Actions <actions@github.com>"

      - name: Pull changes
        run: git pull --rebase origin ${{ github.ref }}
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
